import type { DocumentType } from "./types";
export const roles: Record<DocumentType, string> = {
  purchase_order: "Đơn đặt hàng",
  invoice: "Hóa đơn",
  payment_request: "Đề nghị thanh toán",
  purchase_request: "Đề nghị mua hàng (ngoài phạm vi)",
  unclassified: "Đang nhận diện chứng từ",
  unknown: "Chưa xác định loại chứng từ",
  mixed: "Chứa nhiều loại chứng từ",
};
export const statuses: Record<string, string> = {
  queued: "Đang chờ",
  processing: "Đang phân tích",
  completed: "Hoàn tất",
  failed: "Xử lý lỗi",
  interrupted: "Bị gián đoạn",
  uploaded: "Đã tải lên",
  extracted: "Đã trích xuất",
};
export const assessments: Record<string, string> = {
  review_required: "Cần xem xét",
  incomplete_analysis: "Phân tích chưa đầy đủ",
  no_issues_detected_in_assessed_scope:
    "Chưa phát hiện vấn đề trong phạm vi đã kiểm tra",
};
export const fields: Record<string, string> = {
  document_number: "Số chứng từ",
  invoice_date: "Ngày hóa đơn",
  po_date: "Ngày đặt hàng",
  request_date: "Ngày đề nghị",
  currency: "Tiền tệ",
  due_date: "Hạn thanh toán",
  delivery_date: "Ngày giao hàng",
  payment_terms: "Điều khoản thanh toán",
  "payment_terms.days": "Thời hạn thanh toán (ngày)",
  invoice_value: "Giá trị hóa đơn",
  invoice_amount: "Giá trị hóa đơn",
  "party.address": "Địa chỉ đơn vị",
  "buyer.name": "Bên mua",
  "buyer.address": "Địa chỉ bên mua",
  "supplier.name": "Nhà cung cấp",
  "supplier.address": "Địa chỉ nhà cung cấp",
  "bank.account_number": "Số tài khoản",
  "bank.account_name": "Tên tài khoản",
  "payment.account_number": "Số tài khoản thanh toán",
  "payment.account_name": "Tên tài khoản thanh toán",
  "bank.name": "Ngân hàng",
  "beneficiary.account": "Tài khoản thụ hưởng",
  "approver.name": "Người phê duyệt",
  "issuer.name": "Người phát hành",
  "issuer.role": "Bộ phận / vai trò người phát hành",
  "preparer.name": "Người lập chứng từ",
  "preparer.role": "Bộ phận / vai trò người lập",
  "approval.role": "Vai trò phê duyệt",
  po_reference: "Tham chiếu PO",
  invoice_reference: "Tham chiếu hóa đơn",
  "party.name": "Tên đơn vị",
  "bank.account": "Tài khoản ngân hàng",
  "beneficiary.name": "Tên người thụ hưởng",
  "item.code": "Mã hàng",
  "item.description": "Tên hàng",
  "item.quantity": "Số lượng",
  "item.unit": "Đơn vị tính",
  "item.unit_price": "Đơn giá",
  "item.amount": "Thành tiền",
  subtotal: "Cộng trước thuế",
  tax_rate: "Thuế suất",
  tax_amount: "Tiền thuế",
  total: "Tổng tiền",
  paid_amount: "Đã thanh toán",
  requested_amount: "Đề nghị thanh toán",
  "approval.status": "Trạng thái phê duyệt",
};
